project:
  type: website
  output-dir: docs

website:
  title: "MFRE Data Hub"
  sidebar: 
    style: "docked"
    search: true
    contents: 
      - section: "Python Resources"
        contents:
        - introduction_to_python.ipynb
        - query_function.ipynb
      - section: "R Resources"
        contents:
      - section: "Excel Resources"
        contents:
      - section: "SQL Resources"
        contents:
      - section: "Recommended Data Sources"
        contents:
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/HJIzt/MFRE_Data_Hub
      - icon: twitter
        href: https://twitter.com/mfreUBC?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor

format:
  html:
    theme: cosmo
    css: styles.css



