project:
  type: website
  output-dir: docs

website:
  title: "MFRE Data Hub"
  sidebar: 
    style: "docked"
    search: true
    contents: 
      - section: "Python Resources"
        contents:
        - introduction_to_python.ipynb


      - section: "R Resources"
        contents:

      - section: "Excel Resources"
        contents:

      - section: "SQL Resources"
        contents:

      - section: "Recommended Data Sources"
        contents:

  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com

format:
  html:
    theme: cosmo
    css: styles.css



